### PR TITLE
Add missing CSS weights.

### PR DESCRIPTION
**Pull request by mikebronner**
I'm just stabbing in the dark with these, sorry if it's not fully fleshed out yet (I don't understand where the sketch values are coming from). Thin and Extra Bold work, and I have tested those. Still trying to figure out how to get Heavy to work. I suspect the sketch value is incorrect. Any pointers you can give me to fix this? Thanks!

### CODE REVIEW

**Comment by mikebronner** [comment]
Update: just found this:
```
  static int app_kit_font_weights[] = {
      2,   // FontWeight100
      3,   // FontWeight200
      4,   // FontWeight300
      5,   // FontWeight400
      6,   // FontWeight500
      8,   // FontWeight600
      9,   // FontWeight700
      10,  // FontWeight800
      12,  // FontWeight900
  };
```

 Will be updating the PR in a sec after testing.

**Comment by mikebronner** [comment]
Added some updates ... having problems getting the following weights to work:
- heavy/black
- extra-light

Been testing with the font "Apple SD Gothic Neo". I also added some aliases -- not sure if they are used or not, I always use the CSS weight number (100 - 900). If they are not used, just let me know, and I can remove them again. :)

Open to suggestions and recommendations.

Thanks!

**Comment by mikebronner** [comment]
Example fonts generated:
Screen Shot 2019-11-17 at 6 52 28 PM

**Comment by MaxBazarov** [comment]
Looks good. Thanks.

**Comment by mikebronner** [comment]
Hi @MaxBazarov, thanks for merging this. It looks like these changes were overwritten by a later change, as they are not in the 6.1.0 version anymore. Would you mind re-releasing, or would you like me to resubmit this PR? Thanks! :)

**Comment by MaxBazarov** [comment]
Ohhh. It's my fault. I will fix it right now.

**Comment by MaxBazarov** [comment]
@mikebronner  Re-pushed in 6.1.1  Please check. I hope it will not be a place for try #3.

**Pull request merged**
